export const LOADING = "loading"
export const LOADING_DONE = "loading_done"
export const FEEDBACK_INFO = "feedback_info"
export const FEEDBACK_SUCCESS = "feedback_success"
export const REDIRECT = "redirect"
// Users
export const FETCH_LOGGED_USER = "GET user"
export const FETCH_AUTH_ERRORS = "auth/errors"
export const UPDATE_USER = "PATCH users"
export const FETCH_USERS = "GET users"
export const FETCH_USER = "GET users/id"
export const ADD_USER = "POST users"
// Credentials
export const FETCH_CREDENTIALS = "GET credentials"
export const ADD_CREDENTIALS = "POST credentials"
export const FETCH_SINGLE_CREDENTIALS = "GET credentials/:id"
export const UPDATE_CREDENTIALS = "PATCH credentials/:id"
export const DELETE_CREDENTIALS = "DELETE credentials/:id"
// Boards
export const FETCH_BOARD = "GET boards/:id"
export const FETCH_BOARDS = "GET boards"
export const ADD_BOARD = "POST boards"
export const UPDATE_BOARD = "PATCH boards/:id"
export const DELETE_BOARD = "DELETE boards/:id"
export const FETCH_BOARD_SETTINGS = "GET boards/:id/settings/:date"
export const FETCH_BOARD_TEAMS = "GET boards/:id/teams"
export const UPDATE_BOARD_TEAM_MEMBERS = "PUT boards/:id/teams/:id/members"
export const REORDER_BOARD_TEAMS = "PATCH boards/:id/teams"
// Board items
export const FETCH_BOARD_ITEMS = "GET boards/:id/items"
export const NEW_BOARD_ITEMS = "POST boards/:id/items"
export const REPLACE_BOARD_ITEM = "PUT boards/:id/items/:id"
export const FETCH_BOARD_ASSIGNMENTS = "GET boards/:id/assignments"
export const FETCH_BOARD_MEMBERS = "GET boards/:id/members"
export const ADD_BOARD_MEMBERS = "POST boards/:id/members"
export const DELETE_BOARD_MEMBER = "DELETE boards/:id/members:/:id"
export const UPDATE_BOARD_MEMBER = "PATCH boards/:id/members:/:id"
// Board tools
export const COPY_BOARD_ROW = "BOARD/ROW/COPY"
export const COPY_BOARD_TASKS = "BOARD/TASKS/COPY"
export const BOARD_EDIT_MODE = "BOARD/EDIT_MODE"
export const CHANGE_BOARD_DATE = "BOARD/DATE"
export const BOARD_TASK_ASSIGNMENT = "BOARD/ASSIGNMENT"
export const BOARD_INITIAL_TOOLS = "BOARD/INITIAL_RULES"
export const BOARD_TASK_SEARCH = "BOARD/TASKS/SEARCH"


// Teams
export const FETCH_TEAMS = "GET teams"
export const ADD_TEAM = "POST teams"
export const FETCH_TEAM = "GET team/:id"
export const UPDATE_TEAM = "PATCH teams/:id"
export const DELETE_TEAM = "DELETE teams/:id"
export const FETCH_TEAM_MEMBERS = "GET teams/:id/members"
// Notifications
export const FETCH_NOTIFICATIONS = "GET notifications"
export const DELETE_NOTIFICATION = "DELETE notifications/:id"
export const NEW_NOTIFICATION = "POST notifications/:id"
export const FETCH_NOTIFICATION_UNREAD_COUNT = "GET notifications/unread/count"
// Errors
export const ERROR_DATA = "ERROR/DATA"
export const ERROR_SERVER = "ERROR/SERVER"
export const ERROR_CLIENT = "ERROR/CLIENT"
export const ERROR_DELETE = "ERROR/DELETE"